export const randomPrompts = [
	'A futuristic cityscape with floating buildings and flying cars',
	'A serene beach at sunset, with palm trees and gentle waves',
	'An enchanted forest with vibrant, luminescent plants and magical creatures',
	'A steampunk-inspired metropolis filled with intricate machinery and gears',
	'An underwater kingdom with colorful coral reefs and exotic sea creatures',
	'A mystical mountain range shrouded in mist and ancient ruins',
	'A bustling marketplace in a vibrant, multicultural city',
	'A whimsical, fairytale-like cottage nestled in a field of flowers',
	'A group of playful kittens exploring a pile of colorful toy balls',
	'A majestic white horse galloping through a field of wildflowers',
	"A mischievous squirrel stealing a toy nut from a child's hands",
	'A family of ducks swimming in a pond with floating toy ducks',
	'A teddy bear picnic in a sunlit meadow, surrounded by friendly woodland creatures',
	'A whimsical carousel with beautifully carved wooden animal figures',
	'A curious monkey swinging from tree branches and playing with a toy banana',
	'A magical toy shop filled with stuffed animals, dolls, and mechanical toys',
	'A proud peacock displaying its vibrant feathers next to a toy peacock on a pedestal',
	'A playful puppy tugging at a toy rope while surrounded by colorful rubber balls',
	'A space station orbiting a distant planet, surrounded by stars',
	'A majestic waterfall cascading down a lush green valley',
	'A futuristic sports arena with holographic displays and high-tech equipment',
	'A cozy winter cabin surrounded by snow-covered pine trees',
	'A desert oasis with palm trees, camels, and a shimmering blue pool',
	'A fantastical underwater city with mermaids and intricate architecture',
	'A haunted castle on a hill, with lightning striking in the background',
	'A serene Japanese garden with cherry blossom trees and a tranquil pond',
	'A vibrant carnival with colorful rides, games, and cheerful crowds',
	'A futuristic laboratory filled with cutting-edge technology and scientific equipment',
	'A picturesque vineyard with rows of grapevines and a rustic farmhouse',
	'A mythical creature-filled fantasy landscape with dragons, unicorns, and giants',
];
