import React from 'react';

const Help = () => {
	return (
		<div className="w-full md:h-[77.6vh] home-gradient flex flex-col">
			<h1 className="self-center text-[30px] text-[#ECE0E0] dark:text-black dark-shadow">
				<span className="text-[40px] text-[#7B2789]">F</span>requently{' '}
				<span className="text-[40px] text-[#AD2121]">A</span>sked{' '}
				<span className="text-[40px] text-[#7B2789]">Q</span>uestions
			</h1>
			<h2 className="text-[30px] text-[#ECE0E0] dark:text-black red-glow mb-3 md:ml-28 ml-6">
				What is ArtIfy?
			</h2>
			<p className="text-[20px] md:ml-32 ml-10 font-['Baumans'] dark:text-[#4c4f55]">
				ArtIfy is an online social media service focused{' '}
				<br className="md:hidden flex" />
				on creating and sharing images generated by AI. <br />
				As a member of ArtIfy you can create <br className="md:hidden flex" />
				your own AI generated images and share them with the world!
			</p>
			<h2 className="text-[30px] text-[#ECE0E0] dark:text-black purple-glow mb-3 md:ml-28 ml-6">
				How do I get started?
			</h2>
			<p className="text-[20px] md:ml-32 ml-10 font-['Baumans'] dark:text-[#4c4f55]">
				The only things you need are an account and your imagination! <br />
				After signing in go to "generate" section,
				<br className="md:hidden flex" /> write your prompt in the provided area
				<br className="md:hidden flex" />
				and wait for your words to become art!
			</p>
			<h2 className="text-[30px] text-[#ECE0E0] dark:text-black red-glow mb-3 md:ml-28 ml-6">
				Can I use generated images for commercial purposes?
			</h2>
			<p className="text-[20px] md:ml-32 ml-10 font-['Baumans'] dark:text-[#4c4f55]">
				Yes, you can use the images generated by you{' '}
				<br className="md:hidden flex" />
				on ArtIfy for commercial purposes.
			</p>
			<h2 className="text-[30px] text-[#ECE0E0] dark:text-black purple-glow mb-3 md:ml-28 ml-6">
				Who owns the content generated using ArtIfy?
			</h2>
			<p className="text-[20px] md:ml-32 ml-10 font-['Baumans'] dark:text-[#4c4f55]">
				You own all input provided to the services. Additionally, ArtIfy assigns
				to you all its right,
				<br className="md:hidden flex" /> title, and interest in and to
				<br className="md:flex hidden" />
				output generated and returned by the services based on your input.
				<br />
				Therefore, as a user of ArtIfy you own all the content you generate
				using the platform.
			</p>
		</div>
	);
};

export default Help;
